---
# сначала удаляю пакеты
- name: remove packages and autoremove
  ansible.builtin.apt:
    name: 
    - ntp
    - ntpstat
    state: absent
    autoremove: yes
    purge: true
    
- name: Install systemd-timesyncd
  package:
    name: systemd-timesyncd
#    update_cache: true
  when: not ((ansible_distribution == 'Debian' and ansible_distribution_major_version is version('11', '<')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version('20', '<')))

- name: Set timezone
  timezone:
    name: "{{ timesync_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
